// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBrlaQ_inJDQOdtAKMmkLjyawiUovp7d4',
    appId: '1:510126692584:web:cb374d586abe3f9b1bd15d',
    messagingSenderId: '510126692584',
    projectId: 'safekid-pro',
    authDomain: 'safekid-pro.firebaseapp.com',
    storageBucket: 'safekid-pro.firebasestorage.app',
    measurementId: 'G-8FBZ2DN15Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpZmkd62TBc4hZc-JuzeHBHM4fRGhXPEk',
    appId: '1:510126692584:android:426214f1b3eaf6051bd15d',
    messagingSenderId: '510126692584',
    projectId: 'safekid-pro',
    storageBucket: 'safekid-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj1DX4LdZswyE8d0MQlrr8clGY1zXhgyk',
    appId: '1:510126692584:ios:8983f8fc9897ad0b1bd15d',
    messagingSenderId: '510126692584',
    projectId: 'safekid-pro',
    storageBucket: 'safekid-pro.firebasestorage.app',
    iosBundleId: 'com.example.safekidPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj1DX4LdZswyE8d0MQlrr8clGY1zXhgyk',
    appId: '1:510126692584:ios:8983f8fc9897ad0b1bd15d',
    messagingSenderId: '510126692584',
    projectId: 'safekid-pro',
    storageBucket: 'safekid-pro.firebasestorage.app',
    iosBundleId: 'com.example.safekidPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBrlaQ_inJDQOdtAKMmkLjyawiUovp7d4',
    appId: '1:510126692584:web:e1c73234dbd194991bd15d',
    messagingSenderId: '510126692584',
    projectId: 'safekid-pro',
    authDomain: 'safekid-pro.firebaseapp.com',
    storageBucket: 'safekid-pro.firebasestorage.app',
    measurementId: 'G-GPHJH5XRFM',
  );
}
